allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@thaunknown/simple-peer'
  - '@thaunknown/simple-websocket'
  - 'es-object-atoms'
  - 'immutable'
  - 'semver'
  - 'typed-array-length'
  - 'webrtc-polyfill'
